package lk.ijse.aad67.cropmonitoringsystem_backend.entity;

public enum Designation {
    MANAGER,SENIOR_ASSISTANT_MANAGER,ASSISTANT_MANAGER,ADMIN_HR,OFFICE_ASSISTANT,SENIOR_AGROMOMIST,
    AGRONOMIST,SOIL_SCIENTIST,SENIOR_TECHNICIAN,TECHNICIAN,SUPERVISOR,LABORS
}
